export SECRET_KEY=secret_key
export PROJECT_NAME=task-organizer
export POSTGRES_SERVER=localhost
export POSTGRES_PORT=5432
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=test
export POSTGRES_DB=TaskOrganizer